import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { Heart, ShoppingCart, X } from "lucide-react";
import { ImageWithFallback } from "./figma/ImageWithFallback";
import { Star } from "lucide-react";
export function WishlistPage({ wishlistItems, onRemoveFromWishlist, onAddToCart, onProductClick, onNavigate, }) {
    return (_jsxs("div", { className: "max-w-7xl mx-auto px-4 py-8", children: [_jsxs("h1", { className: "text-3xl mb-8", children: ["My Wishlist (", wishlistItems.length, ")"] }), wishlistItems.length === 0 ? (_jsxs("div", { className: "bg-white rounded-xl border border-gray-200 p-16 text-center", children: [_jsx("div", { className: "w-20 h-20 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-6", children: _jsx(Heart, { className: "w-10 h-10 text-gray-400" }) }), _jsx("h2", { className: "text-2xl mb-4", children: "Your wishlist is empty" }), _jsx("p", { className: "text-gray-600 mb-8", children: "Save items you love for later. They'll be waiting for you here." }), _jsx("button", { onClick: () => onNavigate("products"), className: "px-8 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700", children: "Start Shopping" })] })) : (_jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6", children: wishlistItems.map((product) => (_jsxs("div", { className: "bg-white rounded-xl border border-gray-200 overflow-hidden hover:shadow-lg transition-shadow group relative", children: [_jsx("button", { onClick: () => onRemoveFromWishlist(product.id), className: "absolute top-3 right-3 z-10 w-10 h-10 bg-white rounded-full flex items-center justify-center shadow-md hover:bg-red-50 transition-colors", children: _jsx(X, { className: "w-5 h-5 text-red-600" }) }), _jsx("div", { className: "relative aspect-square overflow-hidden bg-gray-100 cursor-pointer", onClick: () => onProductClick(product.id), children: _jsx(ImageWithFallback, { src: product.image, alt: product.name, className: "w-full h-full object-cover group-hover:scale-105 transition-transform duration-300" }) }), _jsxs("div", { className: "p-4", children: [_jsx("div", { className: "text-sm text-gray-500 mb-1", children: product.brand }), _jsx("h3", { className: "mb-2 line-clamp-2 cursor-pointer hover:text-blue-600 transition-colors", onClick: () => onProductClick(product.id), children: product.name }), _jsxs("div", { className: "flex items-center gap-1 mb-3", children: [_jsx("div", { className: "flex items-center", children: [...Array(5)].map((_, i) => (_jsx(Star, { className: `w-4 h-4 ${i < Math.floor(product.rating)
                                                    ? "fill-yellow-400 text-yellow-400"
                                                    : "text-gray-300"}` }, i))) }), _jsxs("span", { className: "text-sm text-gray-600", children: ["(", product.reviews, ")"] })] }), _jsxs("div", { className: "flex items-baseline gap-2 mb-4", children: [_jsxs("span", { className: "text-blue-600", children: ["$", product.price.toFixed(2)] }), product.originalPrice && (_jsxs("span", { className: "text-sm text-gray-400 line-through", children: ["$", product.originalPrice.toFixed(2)] }))] }), _jsxs("button", { onClick: () => onAddToCart(product), className: "w-full bg-blue-600 text-white py-2 rounded-lg hover:bg-blue-700 transition-colors flex items-center justify-center gap-2", children: [_jsx(ShoppingCart, { className: "w-4 h-4" }), "Add to Cart"] })] })] }, product.id))) }))] }));
}
